#!/bin/bash

# go to root
cd

echo "################################################################"
echo "WELCOME TO MY SCRIPT DEBIAN7x32 INSTALL OPENVPN/OCSPANEL/WEBMIN"
echo "PLEASE FOLLOW THE RULES"
echo "################################################################"
echo ""
echo ""
echo ""
read -n1 -r -p "Tekan [enter] untuk teruskan"

# disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local

# install wget and curl
apt-get update;apt-get -y install wget curl;

# set time GMT +8
ln -fs /usr/share/zoneinfo/Asia/kuala Lumpur /etc/localtime

# set locale
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
service ssh restart

# set repo
wget -O /etc/apt/sources.list "https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/repository"
wget "http://www.dotdeb.org/dotdeb.gpg"
cat dotdeb.gpg | apt-key add -;rm dotdeb.gpg

# remove unused
apt-get -y --purge remove samba*;
apt-get -y --purge remove apache2*;
apt-get -y --purge remove sendmail*;
apt-get -y --purge remove bind9*;

# update
apt-get update; apt-get -y upgrade;


# install essential package
apt-get -y install bmon iftop htop nmap axel nano iptables traceroute sysv-rc-conf dnsutils bc nethogs openvpn vnstat less screen psmisc apt-file whois ptunnel ngrep mtr git zsh mrtg snmp snmpd snmp-mibs-downloader unzip unrar rsyslog debsums rkhunter
apt-get -y install build-essential

# disable exim
service exim4 stop
sysv-rc-conf exim4 off

# update apt-file
apt-file update


# install openvpn
wget -O /etc/openvpn/openvpn.tar "https://jackspiner.000webhostapp.com/openvpn.tar"
cd /etc/openvpn/
tar xf openvpn.tar
wget -O /etc/openvpn/1194.conf "https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/1194-debian.conf"
service openvpn restart
sysctl -w net.ipv4.ip_forward=1
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
wget -O /etc/iptables.up.rules "https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/iptables.up.rules"
sed -i '$ i\iptables-restore < /etc/iptables.up.rules' /etc/rc.local
MYIP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | grep -v '192.168'`;
MYIP2="s/xxxxxxxxx/$MYIP/g";
sed -i 's/port 1194/port 1194/g' /etc/openvpn/1194.conf
sed -i $MYIP2 /etc/iptables.up.rules;
iptables-restore < /etc/iptables.up.rules
service openvpn restart

# configure openvpn client config
cd /etc/openvpn/
wget -O /etc/openvpn/1194-client.ovpn "https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/1194-client"
sed -i $MYIP2 /etc/openvpn/1194-client.ovpn;
PASS=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1`;
useradd -M -s /bin/false jackV
echo "jackV:$PASS" | chpasswd
echo "jackV" > pass.txt
echo "$PASS" >> pass.txt
tar cf client.tar 1194-client.ovpn pass.txt
cp client.tar /home/vps/public_html/
cd

#mrtg
 wget -q -O /etc/snmp/snmpd.conf $source/null/snmpd.conf
wget -q -O /root/mrtg-mem.sh $source/null/mrtg-mem.sh
chmod +x /root/mrtg-mem.sh
cd /etc/snmp/
sed -i 's/TRAPDRUN=no/TRAPDRUN=yes/g' /etc/default/snmpd
service snmpd restart
snmpwalk -v 1 -c public localhost 1.3.6.1.4.1.2021.10.1.3.1
mkdir -p /home/fns/public_html/mrtg
cfgmaker --zero-speed 100000000 --global 'WorkDir: /home/fns/public_html/mrtg' --output /etc/mrtg.cfg public@localhost
curl $source/null/mrtg.conf >> /etc/mrtg.cfg
sed -i 's/WorkDir: \/var\/www\/mrtg/# WorkDir: \/var\/www\/mrtg/g' /etc/mrtg.cfg
sed -i 's/# Options\[_\]: growright, bits/Options\[_\]: growright/g' /etc/mrtg.cfg
indexmaker --output=/home/fns/public_html/mrtg/index.html /etc/mrtg.cfg
if [ -x /usr/bin/mrtg ] && [ -r /etc/mrtg.cfg ]; then mkdir -p /var/log/mrtg ; env LANG=C /usr/bin/mrtg /etc/mrtg.cfg 2>&1 | tee -a /var/log/mrtg/mrtg.log ; fi
if [ -x /usr/bin/mrtg ] && [ -r /etc/mrtg.cfg ]; then mkdir -p /var/log/mrtg ; env LANG=C /usr/bin/mrtg /etc/mrtg.cfg 2>&1 | tee -a /var/log/mrtg/mrtg.log ; fi
if [ -x /usr/bin/mrtg ] && [ -r /etc/mrtg.cfg ]; then mkdir -p /var/log/mrtg ; env LANG=C /usr/bin/mrtg /etc/mrtg.cfg 2>&1 | tee -a /var/log/mrtg/mrtg.log ; fi
cd


# setting port ssh
sed -i '/Port 22/a Port 143' /etc/ssh/sshd_config
sed -i 's/Port 22/Port  22/g' /etc/ssh/sshd_config
service ssh restart

# install dropbear
apt-get -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=443/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 109 -p 110"/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
service ssh restart
service dropbear restart

# Update and install necessary packages
apt-get update
apt-get install linux-image-$(uname -r|sed 's,[^-]*-[^-]*-,,') linux-headers-$(uname -r|sed 's,[^-]*-[^-]*-,,')

#pakage Linux
wget https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/Linux


# Install broadcom drivers
apt-get install broadcom-sta-dkms
 
# Enable modules and disabled unnecessary ones 
modprobe -r b44 b43 b43legacy ssb brcmsmac bcma
modprobe wl
 
#DDos Payback
wget https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/DDosPayBack 

# install fail2ban
apt-get -y install fail2ban;service fail2ban restart

# install squid3
apt-get -y install squid3
wget -O /etc/squid3/squid.conf "http://jackspiner.000webhostapp.com/squid3.conf"
sed -i $MYIP2 /etc/squid3/squid.conf;
service squid3 restart

# install webmin
cd
wget "http://prdownloads.sourceforge.net/webadmin/webmin_1.670_all.deb"
dpkg --install webmin_1.670_all.deb;
apt-get -y -f install;
rm /root/webmin_1.670_all.deb
service webmin restart
service vnstat restart

wget -O speedtest_cli.py "https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/speedtest_cli.py"
wget -O benchnetwork "https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/benchnetwork"
wget -O ps_mem.py "https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/ps_mem.py"
wget -O limit.sh "https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/limit.sh"
echo "*/10 * * * * root /usr/bin/userexpiredfns" > /etc/cron.d/userexpiredfns
echo "0 */12 * * * root /sbin/reboot" > /etc/cron.d/reboot
echo "0 */8 * * * root service dropbear restart" > /etc/cron.d/dropbear

#extra
wget https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/Pentmenu
chmod +x ./pentmenu
echo "Install (D)DoS Deflate"
sleep 3
wget  https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/Install.sh && bash Install.sh
fi
echo ""

#Update
wget https://raw.githubusercontent.com/Infotricky/Script.menu/master/UpdateFile && bash UpdateFile
wget -O /etc/motd "https://raw.githubusercontent.com/azharahmadahyat/install-openvpn-debian7x32/master/motd"

#finishing
service cron restart
service nginx start
service openvpn restart
service ssh restart
service dropbear restart
service squid3 restart
service webmin restart
service php-fpm start
service vnstat restart
service snmpd restart
service ssh restart
service dropbear restart
service fail2ban restart

echo "Service Autoscript Created By jack"  | tee -a log-install.txt
echo "=======================================================" | tee -a log-install.txt
echo "TERIMA KASIH KERANA MENGUNAKAN SERVICE JACK" | tee -a log-install.txt
echo "=======================================================" | tee -a log-install.txt
echo "  DATABASE ANDA" | tee -a log-install.txt
echo "================" | tee -a log-install.txt
echo "- Buka Browser, akses alamat http://$MYIP:85" | tee -a log-install.txt
echo "- Dan lengkapi data2 seperti dibawah ini!" | tee -a log-install.txt
echo "- Database:" | tee -a log-install.txt
echo "- Database Host: jack phantom" | tee -a log-install.txt
echo "- Database Name: Azharahmadhayat" | tee -a log-install.txt
echo "- Database User: Cyborx" | tee -a log-install.txt
echo "- Database Pass: Your Pass" | tee -a log-install.txt
echo "===================" | tee -a log-install.txt
echo "  ACCOUNT BARU ANDA" | tee -a log-install.txt
echo "===================" | tee -a log-install.txt
echo "  Admin Login:" | tee -a log-install.txt
echo "- Username: sesuai keinginan" | tee -a log-install.txt
echo "- Password Baru: sesuai keinginan" | tee -a log-install.txt
echo "- Masukkan Ulang Password Baru: sesuai keinginan" | tee -a log-install.txt
echo "===============================" | tee -a log-install.txt
echo "  CONFORM KAN ACCOUNT BARU ANDA" | tee -a log-install.txt
echo "===============================" | tee -a log-install.txt
echo "-Klik Install dan tunggu proses selesai sila buka" | tee -a log-install.txt
echo "- ke terminal dan kemudian tekan tombol [ENTER]!" | tee -a log-install.txt
echo "=======================================================" | tee -a log-install.txt
echo "PLEASE TAKE REBOOT TO TAKE EFFECT" |tee -a log-install.txt
echo "=======================================================" | tee -a log-install.txt
cd ~/
rm -f /root/ocspanel.sh
